exp_name: LR_L1
dataset_sampling: Uniform
model: 
  name: LogisticRegression
  params:
    l1_ratio: 1
    C: 1.0
    solver: saga
    max_iter: 1000
data:
  evc: 
    data_dict: /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2022_EVC_CONUS/CSV_Data/LF2022_EVC.csv
    raster:  /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2022_EVC_CONUS/Tif/LF2022_EVC_CONUS.tif
  evh: 
    data_dict: /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2022_EVH_CONUS/CSV_Data/LF2022_EVH.csv
    raster:  /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2022_EVH_CONUS/Tif/LF2022_EVH_CONUS.tif
  evt: 
    data_dict: /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2022_EVT_CONUS/CSV_Data/LF2022_EVT.csv
    raster:  /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2022_EVT_CONUS/Tif/LF2022_EVT_CONUS.tif
  bps: 
    data_dict: /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2020_BPS_CONUS/CSV_Data/LF2020_BPS.csv
    raster:  /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/LF2020_BPS_CONUS/Tif/LF2020_BPS_CONUS.tif
  nlcd:
    raster: /home/rpdemilt/SIG/fuels/eo-fuels-extrapolation/data/Annual_NLCD_LndCov_2022_CU_C1V1/Annual_NLCD_LndCov_2022_CU_C1V1.tif
bands:
  aef:
    bands: all
  topography:
    - elevation
    - slope
    - aspect
    - mtpi
  spectral_stats:
    indices:
      - EVI
      - MSAVI
      - NBR
      - NDVI
      - SAVI
      - TCB
      - TCG
      - TSW
      - VARI
    statistics:
      - min
      - mean
      - max
  seasonal_bands:
    bands: 
      - B2
      - B3
      - B4
      - B5
      - B6
      - B7
    seasons: 
      - fall
      - spring
      - summer
      - winter
  climate:
    normals:
      - ppt
      - tmean
      - tmin
      - tmax
      - tdmean
      - vpdmin
      - vpdmax
      - solclear
      - solslope
      - soltotal
    current:
      - ppt
      - tmean
      - tmin
      - tmax
      - tdmean
      - vpdmin
      - vpdmax
  vegetation:
    - evt
    - evh
    - evc
    - bps
    - nlcd

categorical_bands:
  - bps
  - evt
  - nlcd
  
target:
  drop_labels: 
    - 91
    - 92
    - 93
    - 98
    - 99
  label: fbfm40
